/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:93dc9347-e88b-4286-aa84-5fd74537f3e0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RHENvdnrO",
    "aws_user_pools_web_client_id": "4fv9gr74n7mh421a7uvqntipgr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ircskkn2jjdo7pnhkwqsvjxmai.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
